In [1]:
#测试Exp算子
import MyTensor
import numpy as np
from utils.utils import myAssert

for i in range(1000):
    a=MyTensor.MyTensor(np.random.rand(2,3),requires_grad=True)
    Exp=MyTensor.Exp()
    b = Exp.forward(a)
    b.backward()
    myAssert((b.data== a.grad).all(), "something wrong with Exp",b.data,a.grad)

In [ ]:
#简单测试Log
a=MyTensor.MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
Log=MyTensor.Log()
b = Log.forward(a)
b.backward()
print(b.data)
print(a.grad)
print(1/a.data)

In [3]:

#测试Log算子
import MyTensor
import numpy as np
from utils.utils import myAssert
for i in range(1000):
    a=MyTensor.MyTensor(np.random.rand(1,10),requires_grad=True)
    Log=MyTensor.Log()
    b = Log.forward(a)
    b.backward()
    myAssert((a.grad==1/a.data).all(), "something wrong with Log",b.data,a.grad,a.data)

In [2]:
#测试SumUnary算子
from MyTensor import MyTensor,SumUnary
import numpy as np
a=MyTensor(np.random.rand(2,3),requires_grad=True)
Sum=SumUnary(axis=0)
b = Sum.forward(a)
b.backward()
print(b.data)
print(a.grad)


[1.2804597  0.85885145 1.13250734]
[[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
#测试div算子
from MyTensor import MyTensor,Div
import numpy as np
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b=MyTensor(np.array([[2,2,2],[2,2,2]]),requires_grad=True)
Div=Div()
c = Div.forward(a,b)
c.backward()
print(c.data)
print(a.grad)
print(b.grad)


[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[-0.25 -0.5  -0.75]
 [-1.   -1.25 -1.5 ]]
