In [1]:
#测试Exp算子
import MyTensor
import numpy as np
from utils.utils import myAssert

for i in range(1000):
    a=MyTensor.MyTensor(np.random.rand(2,3),requires_grad=True)
    Exp=MyTensor.Exp()
    b = Exp.forward(a)
    b.backward()
    myAssert((b.data== a.grad).all(), "something wrong with Exp",b.data,a.grad)

In [2]:
#简单测试Log
a=MyTensor.MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
Log=MyTensor.Log()
b = Log.forward(a)
b.backward()
print(b.data)
print(a.grad)
print(1/a.data)

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [3]:

#测试Log算子
import MyTensor
import numpy as np
from utils.utils import myAssert
for i in range(1000):
    a=MyTensor.MyTensor(np.random.rand(1,10),requires_grad=True)
    Log=MyTensor.Log()
    b = Log.forward(a)
    b.backward()
    myAssert((a.grad==1/a.data).all(), "something wrong with Log",b.data,a.grad,a.data)