In [14]:
import sys 
import os
# 获取当前工作目录
current_dir = os.getcwd()

# 获取上级目录
parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

In [15]:
#测试Exp算子
from MyTorch import myTensor
from MyTorch.myTensor import MyTensor
import numpy as np
from MyTorch.utils.utils import myAssert

for i in range(1000):
    a=MyTensor(np.random.rand(2,3),requires_grad=True)
    Exp=myTensor.Exp()
    b = Exp.forward(a)
    b.backward()
    myAssert((b.data== a.grad).all(), "something wrong with Exp",b.data,a.grad)

TypeError: 'NoneType' object cannot be interpreted as an integer

In [3]:
#简单测试Log
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
Log=myTensor.Log()
b = Log.forward(a)
b.backward()
print(b.data)
print(a.grad)
print(1/a.data)

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [4]:

#测试Log算子
from MyTorch import MyTensor,myTensor
import numpy as np
from MyTorch.utils.utils import myAssert
for i in range(1000):
    a=MyTensor(np.random.rand(1,10),requires_grad=True)
    Log=myTensor.Log()
    b = Log.forward(a)
    b.backward()
    myAssert((a.grad==1/a.data).all(), "something wrong with Log",b.data,a.grad,a.data)

In [5]:
#测试SumUnary算子
from MyTorch.myTensor import MyTensor,SumUnary
import numpy as np
a=MyTensor(np.random.rand(2,3),requires_grad=True)
Sum=SumUnary(axis=0)
b = Sum.forward(a)
b.backward()
print(b.data)
print(a.grad)


[1.52833191 0.29345969 1.19962171]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#测试div算子
from MyTorch.myTensor import MyTensor,Div
import numpy as np
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b=MyTensor(np.array([[2,2,2],[2,2,2]]),requires_grad=True)
Div=Div()
c = Div.forward(a,b)
c.backward()
print(c.data)
print(a.grad)
print(b.grad)


TypeError: 'NoneType' object cannot be interpreted as an integer

In [7]:
#测试softmax层
from MyTorch.my_nn import Softmax
from MyTorch.myTensor import MyTensor
import torch
import numpy as np
from MyTorch.utils.utils import myAssert    
for i in range(1000):
    for dim in range(2):
        a_np=np.random.rand(2,3)
        a=MyTensor(a_np,requires_grad=True)
        a_torch=torch.tensor(a_np,requires_grad=True)
        softmax=Softmax(dim=dim)
        b=softmax.forward(a)
        b_torch=torch.nn.functional.softmax(a_torch,dim=dim)
        b.backward()
        b_torch.backward(torch.ones_like(b_torch))
        assert np.allclose(b.data,b_torch.detach().numpy())
        myAssert(np.allclose(a.grad,a_torch.grad.detach().numpy()),"something wrong with softmax",a.grad,a_torch.grad.detach().numpy())
print("softmax test passed")

softmax test passed


In [8]:
#relu测试
from MyTorch.my_nn import ReLU
from MyTorch.myTensor import MyTensor
import numpy as np

a=MyTensor(np.array([[-1,2,3],[4,-5,6]]),requires_grad=True)
relu=ReLU()
b=relu.forward(a)
b.backward()
print(b.data)
print(a.grad)

[[0. 2. 3.]
 [4. 0. 6.]]
[[0. 1. 1.]
 [1. 0. 1.]]


In [9]:
from MyTorch.my_nn import ReLU,MLP,Sequential
from MyTorch.myTensor import MyTensor
import numpy as np

a=MyTensor(np.array([[-1,2,3],[4,-5,6]]),requires_grad=False)
model=Sequential(MLP(3,4,2,initial_policy='zeros'),ReLU())
b=model.forward(a)
b.backward()
print(b.data)
print(a.grad)
print(model.layers[0].parameters[0].grad)
print(model)

[[0. 0.]
 [0. 0.]]
None
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Model structure:
   Sequential(
        MLP(3,4,2)
        ReLU()
)


In [10]:
import sys 
import os
# 获取当前工作目录
current_dir = os.getcwd()

# 获取上级目录
parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

In [11]:
import MyTorch.my_nn as nn
import MyTorch.myTensor as MyTensor
from MyTorch.loss_func import NLLLoss 
import numpy as np
a=np.array([[0.1,0.2,0.3,0.4],[0.1,0.2,0.3,0.4]])
b=np.array([1,2])
a=MyTensor.MyTensor(a,requires_grad=True)
b=MyTensor.MyTensor(b,requires_grad=False)
loss=NLLLoss()
c=loss.forward(a,b)
c.backward()
print(c.data)
print(a.grad)

ImportError: cannot import name 'NLLLoss' from 'MyTorch.loss_func' (E:\myTorch\MyTorch\loss_func.py)

In [2]:
#测试logsoftmax
import MyTorch.my_nn as nn
import MyTorch.my_nn as nn
import MyTorch.myTensor as MyTensor
from MyTorch.loss_func import NLLLoss 
import numpy as np
a=np.array([[0.1,0.2,0.3,0.4],[0.1,0.2,0.3,0.4]])
b=np.array([1,2])
a=MyTensor.MyTensor(a,requires_grad=True)
b=MyTensor.MyTensor(b,requires_grad=False)
logsoftmax=nn.LogSoftmax(dim=1)
c=logsoftmax.forward(a)
print(c.data)

[[-1.54253553 -1.44253553 -1.34253553 -1.24253553]
 [-1.54253553 -1.44253553 -1.34253553 -1.24253553]]


In [ ]:
#test mseloss2
#forward result test
import numpy as np
from MyTorch.myTensor import MyTensor
from MyTorch.loss_func import MSEloss2
y_true=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=False)
y_pred=MyTensor(np.array([[1,2,3],[4,5,4]]),requires_grad=True)
criterion=MSEloss2()
result=criterion(y_pred,y_true)
print(result.data)
#backward test
result.backward()
print(y_pred.grad)


0.6666666666666666
[[ 0.          0.          0.        ]
 [ 0.          0.         -0.66666667]]


In [ ]:
#test crossentropyloss2
#forward result test
import numpy as np
from MyTorch.myTensor import MyTensor
from MyTorch.loss_func import CrossEntropyLoss2
y_true=MyTensor(np.array([[1,0,0],[0,1,0]]),requires_grad=False)
y_pred=MyTensor(np.array([[1,0,0],[0,1,0]]),requires_grad=True)
criterion=CrossEntropyLoss2()
result=criterion(y_pred,y_true)
print(result.data)
#backward test
result.backward()
print(y_pred.grad)

-0.5514447139320511
[[ 0.21194156 -0.10597078 -0.10597078]
 [-0.10597078  0.21194156 -0.10597078]]


: 