In [1]:
import sys 
import os
# 获取当前工作目录
current_dir = os.getcwd()

# 获取上级目录
parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

In [2]:
from MyTorch_v2.myTensor import MyTensor,Add
import numpy as np
#构造两个2*3的张量
a = MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b= MyTensor(np.array([[1,2,3],[4,5,6]]))
c=Add.forward(a,b)
print(c.data)
c.backward()
print(a.grad)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1. 1. 1.]
 [1. 1. 1.]]
