In [1]:
#测试Exp算子
from MyTensor import *
import numpy as np
from MyTorch.utils.utils import myAssert

for i in range(1000):
    a=MyTensor.MyTensor(np.random.rand(2,3),requires_grad=True)
    Exp=MyTensor.Exp()
    b = Exp.forward(a)
    b.backward()
    myAssert((b.data== a.grad).all(), "something wrong with Exp",b.data,a.grad)

ImportError: attempted relative import with no known parent package

In [ ]:
#简单测试Log
a=MyTensor.MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
Log=MyTensor.Log()
b = Log.forward(a)
b.backward()
print(b.data)
print(a.grad)
print(1/a.data)

In [3]:

#测试Log算子
import MyTensor
import numpy as np
from utils.utils import myAssert
for i in range(1000):
    a=MyTensor.MyTensor(np.random.rand(1,10),requires_grad=True)
    Log=MyTensor.Log()
    b = Log.forward(a)
    b.backward()
    myAssert((a.grad==1/a.data).all(), "something wrong with Log",b.data,a.grad,a.data)

In [ ]:
#测试SumUnary算子
from MyTensor import MyTensor,SumUnary
import numpy as np
a=MyTensor(np.random.rand(2,3),requires_grad=True)
Sum=SumUnary(axis=0)
b = Sum.forward(a)
b.backward()
print(b.data)
print(a.grad)


In [ ]:
#测试div算子
from MyTensor import MyTensor,Div
import numpy as np
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b=MyTensor(np.array([[2,2,2],[2,2,2]]),requires_grad=True)
Div=Div()
c = Div.forward(a,b)
c.backward()
print(c.data)
print(a.grad)
print(b.grad)


In [ ]:
#测试softmax层
from my_nn import Softmax
from MyTensor import MyTensor
import torch
import numpy as np
from utils.utils import myAssert    
for i in range(1000):
    for dim in range(2):
        a_np=np.random.rand(2,3)
        a=MyTensor(a_np,requires_grad=True)
        a_torch=torch.tensor(a_np,requires_grad=True)
        softmax=Softmax(dim=dim)
        b=softmax.forward(a)
        b_torch=torch.nn.functional.softmax(a_torch,dim=dim)
        b.backward()
        b_torch.backward(torch.ones_like(b_torch))
        assert np.allclose(b.data,b_torch.detach().numpy())
        myAssert(np.allclose(a.grad,a_torch.grad.detach().numpy()),"something wrong with softmax",a.grad,a_torch.grad.detach().numpy())
print("softmax test passed")

In [1]:
#relu测试
from my_nn import ReLU
from MyTensor import MyTensor
import numpy as np

a=MyTensor(np.array([[-1,2,3],[4,-5,6]]),requires_grad=True)
relu=ReLU()
b=relu.forward(a)
b.backward()
print(b.data)
print(a.grad)

[[0. 2. 3.]
 [4. 0. 6.]]
[[0. 1. 1.]
 [1. 0. 1.]]


In [1]:
from my_nn import ReLU,MLP,Sequential
from MyTensor import MyTensor
import numpy as np

a=MyTensor(np.array([[-1,2,3],[4,-5,6]]),requires_grad=False)
model=Sequential(MLP(3,4,2,initial_policy='zeros'),ReLU())
b=model.forward(a)
b.backward()
print(b.data)
print(a.grad)
print(model.layers[0].parameters[0].grad)
print(model)

[[0. 0.]
 [0. 0.]]
None
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Model structure:
   Sequential(
        MLP(3,4,2)
        ReLU()
)
