In [1]:
import sys 
import os
# 获取当前工作目录
current_dir = os.getcwd()

# 获取上级目录
parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

In [2]:
from MyTorch_v2.myTensor import MyTensor,Add
import numpy as np
#构造两个2*3的张量
a = MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b= MyTensor(np.array([[1,2,3],[4,5,6]]))
c=Add.forward(a,b)
print(c.data)
c.backward()
print(a.grad)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
#test for sub
from MyTorch_v2.myTensor import Sub
a = MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b= MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
c=Sub.forward(a,b)
print(c.data)
c.backward()
print(a.grad)
print(b.grad)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-1. -1. -1.]
 [-1. -1. -1.]]


In [4]:
#test for mul
from MyTorch_v2.myTensor import Mul
a = MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b= MyTensor(np.array([[1,2,3],[1,2,3]]),requires_grad=True)
c=Mul.forward(a,b)
print(c.data)
c.backward()
print(a.grad)
print(b.grad)


[[ 1.  4.  9.]
 [ 4. 10. 18.]]
[[1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
#test for matmul
from MyTorch_v2.myTensor import MatMul
# a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
# b=MyTensor(np.array([[1,2],[3,4],[5,6]]),requires_grad=True)
# c=MatMul.forward(a,b)
# # print(c.data)
# c.backward()
# # print(a.grad)
# # print(b.grad)

#test for one_dim_matmul
a=MyTensor(np.array([[1,2,3]]),requires_grad=True)
b=MyTensor(np.array([[1,2],[3,4],[5,6]]),requires_grad=True)
c=MatMul.forward(a,b)
print(c.data)
c.backward()
print(a.grad)
print(b.grad)

[[22. 28.]]
[[ 3.  7. 11.]]
[[1. 1.]
 [2. 2.]
 [3. 3.]]


In [6]:
#test for div
from MyTorch_v2.myTensor import Div
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
c=Div.forward(a,b)
print(c.data)
c.backward()
print(a.grad)
print(b.grad)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[-1.         -0.5        -0.33333333]
 [-0.25       -0.2        -0.16666667]]
