In [1]:
import sys 
import os
# 获取当前工作目录
current_dir = os.getcwd()

# 获取上级目录
parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

In [ ]:
from MyTorch.myTensor import MyTensor,Sum
import numpy as np
#构造两个2*3的张量
a = MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b= MyTensor(np.array([[1,2,3],[4,5,6]]))
c=Sum.forward(a,b)
print(c.data)
c.backward()
print(a.grad)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#test for sub
from MyTorch.myTensor import Sub
a = MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b= MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
c=Sub.forward(a,b)
print(c.data)
c.backward()
print(a.grad)
print(b.grad)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-1. -1. -1.]
 [-1. -1. -1.]]


In [ ]:
#test for mul
from MyTorch.myTensor import Mul
a = MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b= MyTensor(np.array([[1,2,3],[1,2,3]]),requires_grad=True)
c=Mul.forward(a,b)
print(c.data)
c.backward()
print(a.grad)
print(b.grad)


[[ 1.  4.  9.]
 [ 4. 10. 18.]]
[[1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
#test for matmul
from MyTorch.myTensor import MatMul
# a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
# b=MyTensor(np.array([[1,2],[3,4],[5,6]]),requires_grad=True)
# c=MatMul.forward(a,b)
# # print(c.data)
# c.backward()
# # print(a.grad)
# # print(b.grad)

#test for one_dim_matmul
a=MyTensor(np.array([[1,2,3]]),requires_grad=True)
b=MyTensor(np.array([[1,2],[3,4],[5,6]]),requires_grad=True)
c=MatMul.forward(a,b)
print(c.data)
c.backward()
print(a.grad)
print(b.grad)

[[22. 28.]]
[[ 3.  7. 11.]]
[[1. 1.]
 [2. 2.]
 [3. 3.]]


In [ ]:
#test for div
from MyTorch.myTensor import Div
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
c=Div.forward(a,b)
print(c.data)
c.backward()
print(a.grad)
print(b.grad)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[-1.         -0.5        -0.33333333]
 [-0.25       -0.2        -0.16666667]]


In [ ]:
#test for max
from MyTorch.myTensor import Max
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
c=Max.forward(a,axis=1,keepdims=False)
print(c.data)
c.backward()
print(a.grad)

[3. 6.]
[[0. 0. 1.]
 [0. 0. 1.]]


In [ ]:
#test for exp log
from MyTorch.myTensor import Exp,Log
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
c=Exp.forward(a)
print(c.data)
c.backward()
print(a.grad)
d=Log.forward(c)
print(c.data)
d.backward()
print(c.grad)

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[1.36787944 1.13533528 1.04978707]
 [1.01831564 1.00673795 1.00247875]]


In [ ]:
#test for sumunary
from MyTorch.myTensor import SumUnary
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
c=SumUnary.forward(a,axis=1,keepdims=False)
print(c.data)
c.backward()
print(a.grad)

[ 6. 15.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
from MyTorch.loss_func import MSELoss
from MyTorch.myTensor import MyTensor
a=MyTensor(np.array([[1,2,3],[4,5,6]]),requires_grad=True)
b=MyTensor(np.array([[1,2,3],[4,4,6]]),requires_grad=False)
criterion=MSELoss()
c=criterion.forward(a,b)
print(c.data)
c.backward()
print(a.grad)

1.0
[[0. 0. 0.]
 [0. 2. 0.]]


In [ ]:
#a small test
#y=3x+9
from MyTorch.myTensor import MyTensor
from MyTorch.my_nn import MyLinearLayer,Sequential,ReLU
from MyTorch.loss_func import MSELoss
from MyTorch.optim import Adam
from torch.utils.tensorboard import SummaryWriter
# 创建 TensorBoard 日志记录器
writer = SummaryWriter('runs/gradient_tracking')
model=MyLinearLayer(2,2,initial_policy="zeros")
criterion=MSELoss()
optimizer=Adam(model.parameters)

epochs=10000
for i in range(epochs):
    input_np=np.random.randn(2)
    # input_np=np.array([[1,2]])
    target_np=0.5*input_np+0.3
    input=MyTensor(input_np)
    output=model.forward(input)
    target=MyTensor(target_np)
    loss=criterion.forward(output,target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(loss.data)
    writer.add_histogram("weight",model.parameters[0].data,i)
    writer.add_histogram("bias",model.parameters[1].data,i)
    writer.add_histogram("loss",loss.data,i)
print(model(MyTensor(np.array([[0.5,-0.6]]))).data)
writer.close()


0.1757221328089835
1.4284753674572401
0.025446535231857824
0.7948372919671034
0.32358080612427204
1.3566905527731077
1.0228767204043265
0.23793569185193503
0.37213116295389226
0.3626021127090222
1.270239654949301
0.24575134652942565
0.6439753663536353
0.17112116266626534
0.4629066032877539
1.5910423451218956
1.5718293913061996
0.749707648058688
0.9641458392308555
1.3856726760911169
0.14539888495701428
1.4947254334872406
0.08299960622763583
1.7598194318281208
0.9622978602448736
0.6112995672554271
1.6014059647968049
0.6438098771463634
0.04074790817711842
1.206490410096054
0.38137776680914165
0.025312439546372936
0.24433142946418762
0.11120155025107377
0.31376248852501043
0.26778077265349265
0.49404261432795454
0.41931430689105165
0.7782341500621227
0.423924310804626
1.0386192825626177
0.019190425583131533
0.1470135313827138
0.7375526456262889
0.4053968559439738
0.19255931313786254
1.3770927013200205
1.1835390736516747
0.1721189425776027
0.13772686450298813
0.08140589912308359
0.462285068